import * as fs from 'fs'
import * as path from 'path'
import { buildGeneratedDotenvContent } from 'runenv-shared/dotenv'
import * as vscode from 'vscode'
import { getToken, loadProjectConfigContext } from '../config'
import { fetchCliSecrets } from '../core/api-client'
import { getExtensionState } from '../core/extension-state'
import { getEnvFilePreset, resolveEnvFilePresetId } from '../env-files'
import { showError } from '../helpers/error'
import { ensureGitignore, type GitignoreStatus } from '../helpers/gitignore'
import { getProfileMeaning, pickEnvFileProfile } from '../helpers/pickers'
import {
  confirmGeneratePreview,
  showGenerateCompletionPicker,
  showGenerateResultSummary,
} from './generate-dotenv-ui'
import { buildGenerateResultContent } from '../preview'

export async function cmdGenerateDotenv() {
  const { clearLastIssue, recordRecentAction } = getExtensionState()
  const token = getToken()
  if (!token) {
    vscode.window.showErrorMessage(vscode.l10n.t('You need to log in first.'))
    return
  }

  const projectContext = loadProjectConfigContext()
  if (!projectContext) {
    vscode.window.showErrorMessage(
      vscode.l10n.t('This folder is not connected to a RunEnv project yet.')
    )
    return
  }
  const { workspaceRoot, ...project } = projectContext

  const presetId = resolveEnvFilePresetId(project.preset)
  const profile = await pickEnvFileProfile(project.env, presetId, {
    placeHolder: vscode.l10n.t(
      'Choose the kind of file you want RunEnv to create for this workspace'
    ),
    allowTemplate: true,
  })
  if (!profile) return

  try {
    const data = await fetchCliSecrets(token, project.project, project.env, {
      presetId,
      profileId: profile.id,
      resolve: false,
    })
    const outputPath = path.join(workspaceRoot, profile.filename)
    const overwrite = fs.existsSync(outputPath)
    const previewKeys =
      profile.id === 'example'
        ? data.blueprintKeys?.map((item) => item.key) || Object.keys(data.secrets)
        : Object.keys(data.secrets)

    const shouldWrite = await confirmGeneratePreview({
      filename: profile.filename,
      fullPath: outputPath,
      project: project.project,
      env: project.env,
      presetTitle: getEnvFilePreset(presetId).title,
      profile,
      keys: previewKeys,
    })
    if (!shouldWrite) return

    let gitignoreStatus: GitignoreStatus = 'notNeeded'

    if (profile.id === 'example') {
      const header = [
        '# Generated by RunEnv',
        `# Project: ${project.project}/${project.env}`,
        `# Preset: ${getEnvFilePreset(presetId).title}`,
        '# Template only. Fill values locally or in CI.',
        '',
      ]
      const exampleLines =
        data.blueprintKeys && data.blueprintKeys.length > 0
          ? data.blueprintKeys.flatMap((item) =>
              item.description
                ? [`# ${item.description}`, `${item.key}=`, '']
                : [`${item.key}=`, '']
            )
          : Object.keys(data.secrets).flatMap((key) => [`${key}=`, ''])

      fs.writeFileSync(
        outputPath,
        `${header.join('\n')}${exampleLines.join('\n')}\n`,
        {
          mode: 0o600,
        }
      )
      vscode.window.showInformationMessage(
        vscode.l10n.t(
          'RunEnv created {0}. You can share this template safely.',
          profile.filename
        )
      )
      await recordRecentAction(
        'Generate .env File',
        `${profile.filename} template for ${project.project}/${project.env}`,
        'success',
        'runenv.generateDotenv',
        buildGenerateResultContent({
          filename: profile.filename,
          fullPath: outputPath,
          project: project.project,
          env: project.env,
          presetTitle: getEnvFilePreset(presetId).title,
          profileLabel: profile.title,
          profileDescription: getProfileMeaning(profile),
          overwrite,
          keys: [...previewKeys].sort(),
          gitignoreStatus,
          safeToShare: true,
        })
      )
      clearLastIssue()
      await showGenerateResultSummary({
        filename: profile.filename,
        fullPath: outputPath,
        project: project.project,
        env: project.env,
        presetTitle: getEnvFilePreset(presetId).title,
        profile,
        overwrite,
        keys: previewKeys,
        gitignoreStatus,
      })
      await showGenerateCompletionPicker({
        outputPath,
        filename: profile.filename,
      })
      return
    }

    fs.writeFileSync(
      outputPath,
      buildGeneratedDotenvContent({
        project: project.project,
        envName: project.env,
        secrets: data.secrets,
        refreshCommand: 'RunEnv: Generate .env File',
        extraHeaderLines: [
          `# Preset: ${getEnvFilePreset(presetId).title}`,
          `# Profile: ${profile.filename}`,
        ],
      }),
      { mode: 0o600 }
    )

    gitignoreStatus = ensureGitignore(workspaceRoot, profile.filename)
    vscode.window.showInformationMessage(
      vscode.l10n.t(
        'RunEnv created {0} with {1} value{2}.',
        profile.filename,
        Object.keys(data.secrets).length,
        Object.keys(data.secrets).length === 1 ? '' : 's'
      )
    )
    await recordRecentAction(
      'Generate .env File',
      `${profile.filename} for ${project.project}/${project.env}`,
      'success',
      'runenv.generateDotenv',
      buildGenerateResultContent({
        filename: profile.filename,
        fullPath: outputPath,
        project: project.project,
        env: project.env,
        presetTitle: getEnvFilePreset(presetId).title,
        profileLabel: profile.title,
        profileDescription: getProfileMeaning(profile),
        overwrite,
        keys: Object.keys(data.secrets).sort(),
        gitignoreStatus,
        safeToShare: false,
      })
    )
    clearLastIssue()
    await showGenerateResultSummary({
      filename: profile.filename,
      fullPath: outputPath,
      project: project.project,
      env: project.env,
      presetTitle: getEnvFilePreset(presetId).title,
      profile,
      overwrite,
      keys: Object.keys(data.secrets),
      gitignoreStatus,
    })
    await showGenerateCompletionPicker({
      outputPath,
      filename: profile.filename,
    })
  } catch (err) {
    showError(vscode.l10n.t('Failed to generate env file'), err)
  }
}
export {
  autoDetectFlutterProject,
  cmdSetupFlutterDebug,
} from './flutter-debug'
