'use strict'

const GENERATED_DOTENV_HEADER = '# Generated by RunEnv — DO NOT COMMIT'

function formatDotenvValue(value) {
  const normalizedValue = String(value)
  const needsQuote = /[\s#"'\\$`!]/.test(normalizedValue)
  return needsQuote
    ? `"${normalizedValue.replace(/"/g, '\\"')}"`
    : normalizedValue
}

function buildDotenvAssignments(secrets) {
  return Object.entries(secrets)
    .map(([key, value]) => `${key}=${formatDotenvValue(value)}`)
    .join('\n')
}

function buildGeneratedDotenvContent(options) {
  const extraHeaderLines = Array.isArray(options.extraHeaderLines)
    ? options.extraHeaderLines.filter((line) => typeof line === 'string' && line.length > 0)
    : []
  const header = [
    GENERATED_DOTENV_HEADER,
    `# Project: ${options.project} | Environment: ${options.envName}`,
    ...extraHeaderLines,
    `# Run "${options.refreshCommand || 'runenv dotenv'}" to refresh`,
    '',
  ].join('\n')
  const body = buildDotenvAssignments(options.secrets)

  return `${header}${body ? `\n${body}` : ''}\n`
}

module.exports = {
  GENERATED_DOTENV_HEADER,
  formatDotenvValue,
  buildDotenvAssignments,
  buildGeneratedDotenvContent,
}
