export const GENERATED_DOTENV_HEADER: '# Generated by RunEnv — DO NOT COMMIT'

export function formatDotenvValue(value: string): string

export function buildDotenvAssignments(
  secrets: Record<string, string>
): string

export function buildGeneratedDotenvContent(options: {
  project: string
  envName: string
  secrets: Record<string, string>
  refreshCommand?: string
  extraHeaderLines?: string[]
}): string
